---
- name: restart sshd
  ansible.builtin.systemd:
    name: ssh
    state: restarted

- name: apply sysctl
  ansible.builtin.command:
    cmd: sysctl -p /etc/sysctl.d/99-hardening.conf
  changed_when: true

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted

- name: restart auditd
  ansible.builtin.service:
    name: auditd
    state: restarted

- name: reload postfix
  ansible.builtin.systemd:
    name: postfix
    state: reloaded
  failed_when: false
